twitterangular/config/routes.rb
Rails.application.routes.draw do

  get "/moderator" =>"tweets#moderator"
  get "/admin" => "tweets#admin"
  get "/admin_stat" => "tweets#admin_stat"
  get "/tweets/tweet_stat" => "tweets#tweet_stat"
  get "/tweets/all_tweets" => "tweets#all_tweets"
  get "tweets/setStatus" => "tweets#set_status"
  get '/tweets/dashboard' => 'tweets#dashboard'
  get "/user_desg_set" => "users#user_desg_set"
  get "/users/allUsers" => "users#allUsers"
  get "/users/set_desg" => "users#set_desg"
  get "/moderatorview" => "tweets#moderatorview"
  get "/users/signin_func" => "users#signin_func"
  get "/users/check" => "users#check"
  get "/users/checkmail" => "users#checkmail"
  get "/users/getimage" => "users#getimage"
  get "/userpage" => "users#userpage"
  resources :tweets
  get 'users/usertweetsang' => 'users#usertweetsang'

  resources :users do
    get 'usertweets' => 'users#usertweets'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

twitterangular/app/models/tweet.rb
class Tweet < ApplicationRecord
	validates :text, presence: true
	mount_uploader :image, ImageUploader
	belongs_to :user
end

twitterangular/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :getusr, only: [:create]
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  def moderator
  end
  
  def admin
  end

  def show
  end

  def tweet_stat
    todate =  Date.today.to_s
    @tweets = Tweet.where("created_at like '" +todate +"%' and status like 'active'")
    if(!(@tweets.nil?))
      today_active = @tweets.length
    else
      today_active = 0
    end
    @tweets = Tweet.where("created_at like '" +todate +"%' and status like 'inactive'")
    if(!(@tweets.nil?))
      today_inactive = @tweets.length
    else
      today_inactive = 0
    end
    @tweets = Tweet.where("status like 'active'")
    if(!(@tweets.nil?))
      total_active = @tweets.length
    else
      total_active = 0
    end
    @tweets = Tweet.where("status like 'inactive'")
    if(!(@tweets.nil?))
      total_inactive = @tweets.length
    else
      total_inactive = 0
    end
    #obj = ["today_active" : today_active , "today_inactive" : today_inactive , "total_active" : total_active , "total_inactive" : total_inactive ]
    obj =[today_active,today_inactive,total_active,total_inactive]
    render json: obj
  end

  def set_status
    @tweet = Tweet.find(params[:id])
    @tweet.status = params[:status]
    if @tweet.update_attributes(:status => params[:status])
      render json: ["status": "updated"]
    else
      render json: ["status": "failed"]
    end
  end
  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  def dashboard
    @twts= Tweet.where("status='active'").order(created_at: :desc, updated_at: :desc)
    @g=[]
    @twts.each do |t|
      @g.push(User.find_by username: t.username)
      puts @g
    end
    render json: {cont: @twts, dp:@g}
  end
  # GET /tweets/1/edit
  def edit
  end

  def moderatorview
  end

  def all_tweets
    if(params[:status] == "all")
      render json: Tweet.all
    else
      render json: Tweet.where("status like '" + params[:status] +"'")
    end
  end
  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.status="inactive"
    puts "aaaaa"
    puts @usr
    puts "aaaa"
    @tweet.username=@usr[:username]
    #@usr.tweets << [@tweet]
    @tweet['user_id'] = @usr[:id]
    puts @tweet[:image]
    puts "AAAAAAAAAAAAA"
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to userpage_path, notice: 'Tweet has been submitted for approval.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
      end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:username, :text, :status, :approvedby, :image)
    end
    def getusr
      @usr=User.where("username='"+session['username']+"'")[0]
    end
end

twitterangular/app/helpers/tweets_helper.rb
module TweetsHelper
end

twitterangular/app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :tweet_text %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :tweet_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

twitterangular/app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

twitterangular/app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Text</th>
      <th>Status</th>
      <th>Approvedby</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.username %></td>
        <td><%= tweet.text %></td>
        <td><%= tweet.status %></td>
        <td><%= tweet.approvedby %></td>
        <td><%= tweet.image %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<a href = "http://localhost:3000/tweets/new"> new tweet</a>

twitterangular/app/views/tweets/new.html.erb
<html >
<head>
  <script src="/javascripts/tweetnew.js"></script>
</head>
<body >
<h1>Dashboard</h1>


<form enctype="multipart/form-data" action="/tweets" accept-charset="UTF-8" method="post"><input name="utf8" value="✓" type="hidden"><input name="authenticity_token" value="yjwni7sED1tnnDiZQISxzijJRAZ3/xkaWpbHCt+0aPQIBndeaKKDlL6nIN0YBhLm7Iby+kg8MwmTvx7aOY4neQ==" type="hidden">

  <div class="field">
    <input id="tweet_text" name="tweet[text]" type="text" placeholder="Tweet Something">
  </div>

  <div class="field">
    <label for="tweet_image" id="upl"> Upload Image</label><input id="tweet_image" name="tweet[image]" type="file">
  </div>

  <div class="actions">
    <input name="commit" value="Tweet" data-disable-with="Create Tweet" type="submit">
  </div>
</form>
<a href="/tweets">Back</a>

<h3>Tweets</h3>
<div>
    <div id="nw" ng-init="i=-1">
      <div ng-repeat="tweet in tweets" ng-init="i=i+1">
        <div id="tw">
          <span class="" ng-if="dop[i].dp.thumb.url">
            <img src={{dop[i].dp.thumb.url}}></img>
            <!-- <img src="fallback/thumb_default.jpeg"></img> -->
          </span>
          <span class="un"> {{tweet.username}} </span><span class="dt">{{tweet.created_at | date:'MMM dd'}} </span>
          <br>
          {{tweet.text}} <br>
          <div ng-if="imgnull(tweet)">
            <img src={{tweet.image.thumb.url}}></img>
          </div>
        </div>
        <br>
        <br>
      </div>
    </div>
  </div>
</div>
</body>

twitterangular/app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @tweet.username %>
</p>

<p>
  <strong>Text:</strong>
  <%= @tweet.text %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tweet.status %>
</p>

<p>
  <strong>Approvedby:</strong>
  <%= @tweet.approvedby %>
</p>

<p>
  <strong>Image:</strong>
  <%= @tweet.image %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>